version: 2.1
orbs:
  heroku: circleci/heroku@1
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          app-name: freefrom-map-frontend-staging
          filters:
            branches:
              only: staging
      - heroku/deploy-via-git:
          app-name: freefrom-map-frontend-prod
          filters:
            branches:
              only: prod
