version: 2.1
orbs:
  heroku: circleci/heroku@1
workflows:
  heroku_deploy:
    jobs:
      heroku/deploy-via-git:
        filters:
          branches:
            only:
              - circleci
              - staging
