import React from 'react'
import SharedLayout from 'components/SharedLayout'
import BackButton from "components/navigation/BackButton";

export default function PrivacyPolicy() {
    return (
        <SharedLayout>
            <BackButton className="mt-3 mb-2" />
            <h1>Privacy Policy</h1>
            <p>Effective date: March 1, 2021</p>
            <p>FreeFrom (“us“, “we“, or “our“) operates the National Survivor Wealth Policy Map and Scorecard (hereinafter referred to as the “Site“).</p>
            <p>This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Site and the choices you have associated with that data.</p>
            <p>Please read this policy carefully to understand our policies and practices regarding your information and how we will treat it. By accessing or using this Site, you agree to this Privacy Policy.</p>

            <h2>Definitions</h2>
            <h3>Site</h3>
            <p>The site is the National Survivor Wealth Policy Map and Scorecard operated by FreeFrom.</p>
            <h3>Personal Data</h3>
            <p>Personal Data means data about a living individual who can be identified from that data (or from that and other information in our possession or likely to come into our possession).</p>
            <h3>Usage Data</h3>
            <p>Usage Data is data collected automatically either generated by the use of the Site or from the Site infrastructure itself (for example, the duration of a page visit).</p>
            <h3>Cookies</h3>
            <p>Cookies are small files stored on your device (computer or mobile device).</p>

            <h2>Information We Collect About You and How We Collect It</h2>
            <p>We collect different types of information from and about users of our Site.</p>
            <h3>Types of Data Collected</h3>
            <h4>PERSONAL DATA</h4>
            <p>While using our Site, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data“). Personally identifiable information may include, but is not limited to:</p>
            <ul>
                <li>Email address</li>
                <li>Cookies and Usage Data</li>
            </ul>
            <p>We may use your Personal Data to contact you with emails, materials, and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send or by contacting us</p>
            <h4>USAGE DATA</h4>
            <p>We may also collect information on how the Site is accessed and used (“Usage Data“). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Site that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            <h4>TRACKING COOKIES DATA</h4>
            <p>We use cookies and similar tracking technologies to track the activity on our Site and we hold certain information.</p>
            <p>A cookie is a small file placed on the hard drive of your computer. You may refuse to accept browser cookies by activating the appropriate setting on your browser. However, if you select this setting you may be unable to access certain parts of our Site.</p>

            <h2>Use of Data</h2>
            <p>We use the collected data for various purposes:</p>
            <ul>
                <li>To present our Site and its contents to you</li>
                <li>To allow you to participate in interactive features of our Site when you choose to do so</li>
                <li>To gather analysis or valuable information so that we can improve our Site</li>
                <li>To monitor the usage of our Site</li>
                <li>To detect, prevent, and address technical issues</li>
                <li>To communicate with you about your experience after you leave our Site, such as sending you short follow-up surveys about your pursuit of compensation and sending you newsletters to keep you informed of our work unless you have opted not to receive such information</li>
                <li>In any other way we may describe with you provide the information</li>
                <li>For any other purpose with your consent</li>
            </ul>

            <h2>Transfer of Data</h2>
            <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
            <p>If you are located outside of the United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.</p>
            <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
            <p>We will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

            <h2>Disclosure of Data</h2>
            <h3>Disclosure for Law Enforcement</h3>
            <p>Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (for example, a court of a government agency).</p>
            <h3>Legal Requirements</h3>
            <p>We may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul>
                <li>Comply with a legal obligation</li>
                <li>Protect and defend our rights or property</li>
                <li>Prevent or investigate possible wrongdoing in connection with the Site</li>
                <li>Protect the personal safety of users of the Site or the public</li>
                <li>To protect against legal liability</li>
            </ul>

            <h2>Security of Data</h2>
            <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. Although we do our best to protect your personal information, we cannot guarantee the security of your personal information transmitted to our Site.</p>

            <h2>Our Policy on “Do Not Track“ Signals under the California Online Protection Act (CalOPPA)</h2>
            <p>We do not support Do Not Track (“DNT“). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked. You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>

            <h2>Third Parties</h2>
            <p>We may employ third party companies and individuals to facilitate our Site, provide the Site on our behalf, perform Site-related services or assist us in analyzing how our Site is used.</p>
            <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
            <h3>Analytics</h3>
            <p>We may use third parties to monitor and analyze the use of our Site.</p>
            <h4>GOOGLE ANALYTICS</h4>
            <p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Site. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>
            <p>You can opt-out of having made your activity on the Site available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity.</p>
            <p>For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: <a href="https://policies.google.com/privacy?hl=en" target="_blank">https://policies.google.com/privacy?hl=en</a>.</p>

            <h2>Links to Other Sites</h2>
            <p>Our site may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

            <h2>Children's Privacy</h2>
            <p>Our Site is not intended for children under the age of 18. We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are award that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>

            <h2>Changes to this Policy</h2>
            <p>We may update our Privacy Policy from time to time. It is our policy to post any changes we make to our Privacy Policy on this page. If we make changes, we will notify you by revising the date at the top of the policy. We encourage you to review the Privacy Policy whenever you access the Site or otherwise interact with us to stay informed about our information practices and the choices available to you.</p>

            <h2>Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, please contact us by email at: <a href="mailto:info@freefrom.org">info@freefrom.org</a>.</p>

        </SharedLayout>
    )
}
